plugins {
    id 'com.android.application'
    id 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin'
    id 'com.google.gms.google-services'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.firelogin'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.firelogin"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
       viewBinding true
    }
    lint {
        baseline = file("lint-baseline.xml")
    }



}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:32.8.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-appcheck'
    implementation 'com.google.firebase:firebase-appcheck-debug'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'
    testImplementation 'junit:junit:4.13.2'


    //reselctor de pais y estado
    implementation 'com.github.mukeshsolanki:country-picker-android:2.0.1'
    implementation 'org.osmdroid:osmdroid-android:6.1.11'

    implementation 'com.google.android.gms:play-services-gcm:17.0.0'
    implementation 'io.michaelrocks:libphonenumber-android:8.13.52'
    implementation 'com.github.joielechong:countrycodepicker:2.4.1'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.10.0'

     //implementation 'org.jetbrains.kotlinx:kotlinx-serialization-core:1.5.1'
    //implementation 'org.jetbrains.kotlinx:kotlinx-serialization-core:1.6.3'
    //implementation 'org.jetbrains.kotlinx:kotlinx-serialization-core:1.5.1'
    implementation 'androidx.core:core-ktx:1.7.0'

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.2'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.2'
    implementation 'androidx.navigation:navigation-fragment:2.8.9'
    implementation 'androidx.navigation:navigation-ui:2.8.9'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.gms:play-services-maps:19.1.0'
    //implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    implementation 'androidx.multidex:multidex:2.0.1'
implementation 'com.google.android.material:material:1.12.0'

    //implementation (platform("com.google.firebase:firebase-bom:32.8.0"))
    implementation 'com.google.firebase:firebase-auth:21.0.5'
    implementation 'com.google.firebase:firebase-analytics:21.2.0'
    implementation 'com.google.firebase:firebase-database:20.0.3'
    implementation 'com.google.firebase:firebase-firestore:24.4.0'

    // Librería para el carrusel
    implementation 'me.relex:circleindicator:2.1.6'
    implementation 'org.imaginativeworld.whynotimagecarousel:whynotimagecarousel:2.1.0'

    //Librería para el calendario
    //implementation 'com.applandeo:material-calendar-view:1-7-0'

    //grupos
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'

    implementation 'com.google.firebase:firebase-database:20.0.5'
    implementation 'com.google.firebase:firebase-storage:20.2.0'
    implementation 'com.google.android.gms:play-services-tasks:18.0.2'
    implementation 'com.github.bumptech.glide:glide:4.12.0'

    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'


}

apply plugin: 'com.google.gms.google-services' // Asegúrate de aplicarlo al final
